package dataexchange

import (
	"context"
	"encoding/json"
	"fmt"
	"html"
	"strings"
	"time"

	"github.com/yixian-huang/navax/internal/navigation"
)

func (s *Service) Export(ctx context.Context, actor navigation.Actor, pageID, format string) (ExportFile, error) {
	page, err := navigation.NewService(navigation.NewSQLStore(s.db)).PageDraft(ctx, actor, pageID)
	if err != nil {
		return ExportFile{}, err
	}
	now := s.now().UTC()
	stamp := now.Format("20060102-150405")
	switch format {
	case FormatNavaxJSON:
		content, err := json.MarshalIndent(PortableExport{Format: "navax-export", Version: 1, ExportedAt: now, Page: page}, "", "  ")
		if err != nil {
			return ExportFile{}, fmt.Errorf("encode navax export: %w", err)
		}
		content = append(content, '\n')
		return ExportFile{ContentType: "application/json; charset=utf-8", Filename: "navax-" + stamp + ".json", Content: content}, nil
	case FormatBookmarksHTML:
		return ExportFile{
			ContentType: "text/html; charset=utf-8", Filename: "navax-bookmarks-" + stamp + ".html",
			Content: []byte(renderBookmarksHTML(page, now)),
		}, nil
	default:
		return ExportFile{}, fmt.Errorf("%w: format must be navax-json or bookmarks-html", ErrValidation)
	}
}

func renderBookmarksHTML(page navigation.Page, exportedAt time.Time) string {
	// Bookmarks HTML only exports currently-enabled navigation (9.2-A).
	byCategory := make(map[string][]navigation.Site, len(page.Categories))
	for _, site := range page.Sites {
		if !site.Enabled {
			continue
		}
		byCategory[site.CategoryID] = append(byCategory[site.CategoryID], site)
	}
	var output strings.Builder
	output.WriteString("<!DOCTYPE NETSCAPE-Bookmark-file-1>\n")
	output.WriteString("<!-- Generated by nav.ax at ")
	output.WriteString(exportedAt.Format(time.RFC3339))
	output.WriteString(" -->\n<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">\n")
	output.WriteString("<TITLE>")
	output.WriteString(html.EscapeString(page.Title))
	output.WriteString("</TITLE>\n<H1>")
	output.WriteString(html.EscapeString(page.Title))
	output.WriteString("</H1>\n<DL><p>\n")
	for _, category := range page.Categories {
		if !category.Enabled {
			continue
		}
		sites := byCategory[category.ID]
		if len(sites) == 0 {
			continue
		}
		output.WriteString("    <DT><H3>")
		output.WriteString(html.EscapeString(category.Name))
		output.WriteString("</H3>\n    <DL><p>\n")
		for _, site := range sites {
			output.WriteString("        <DT><A HREF=\"")
			output.WriteString(html.EscapeString(site.URL))
			output.WriteString("\">")
			output.WriteString(html.EscapeString(site.Title))
			output.WriteString("</A>\n")
		}
		output.WriteString("    </DL><p>\n")
	}
	output.WriteString("</DL><p>\n")
	return output.String()
}
